### ISSUE TITLE
C24a: Duplicate search: read the patients only once and keep only the necessary data in memory

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#101]

**Comment by fbinfotel** [comment]
I started working on the issue on 25/08/2021 . The code can be found on this repo : https://github.com/infotel4iarc/CanReg5/tree/feature/C24a

I have tested the duplicate search using the patient.tsv file from the import CanReg Dataset.

**Comment by fbinfotel** [comment]
The functionality has been implemented.
The generated files are identical between the old and the new duplicate search but the processing time has been greatly reduced

**Comment by fbinfotel** [comment]
the branch has been reviewed and merged with the dev branch here https://github.com/infotel4iarc/CanReg5/tree/dev
