### ISSUE TITLE
C312: The user should be at least invited to change the default value after a SUPERVISOR has reset it

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#105]

**Comment by fbinfotel** [comment]
The branch is https://github.com/infotel4iarc/CanReg5/tree/feature/C312

Here are the point that were done :

- adding a new window after the user connection to remind the user to change his password in case of reset 
- adding french and english traduction for the new fields
- creation of a new file password_reminder.properties in the server side to store the passwordReminder property when a supervisor reset a password
