### ISSUE TITLE
C3134: define default credentials in a configuration file

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#108]
If some default usernames and passwords are required, maybe they could be defined in a configuration file, and the user could be invited to change or override them them during the installation

**Comment by fbinfotel** [comment]
The branch is https://github.com/infotel4iarc/CanReg5/tree/feature/C3134

Here are the point that were done :

- create a file config.properties to store the hardcoded password in the code
- add a paragraph in the instruction (see [[C3134]   instruction change.txt](https://github.com/IARC-CSU/CanReg5/files/7216337/C3134.instruction.change.txt))

**Comment by fbinfotel** [comment]
The branch has not been merged to the dev branch, but it was rebase with the last dev branch (commit 783cd5fa). So it is fully compatible with that dev branch.
If this branch is merged the user should be carefully informed of the possible issues
