### ISSUE TITLE
C212: A transaction should be used when storing the data Patient + Tumours + Sources

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#111]
There is no explicit handling of the database transaction.
The default configuration is “auto-commit”: each statement is in a separate transaction. http://db.apache.org/derby/docs/10.15/devguide/cdevconcepts19173.html
This can be a problem when several database updates should be handled as an atomic operation. For example, a successful first update followed by a failed second update would let the database in an inconsistent state.

**Comment by fbinfotel** [comment]
The branch C212 has been merged to the dev branch
