### ISSUE TITLE
C221: Check every exception in the code and decide what should be done: just log, or display an alert or an error in the GUI

### ISSUE THREAD

**Issue by infotel4iarc** [IARC-CSU/CanReg5#113]
Some exceptions are logged without giving any feedback to the user.
For example, in RecordEditor#saveAllAction, if the save of the Patient or the Tumour or the Source fails, then an exception is only logged, but the error is not displayed in the GUI and the user is not aware that some data are not saved in the database: the user is going to leave the editor and will find out, or not, later that something went wrong.
If the application alerts the user that something went wrong, in some cases, the user will be able to try again, or if the error persists, the user will be able to report the error to the support team.

**Comment by fbinfotel** [comment]
The branch is https://github.com/infotel4iarc/CanReg5/tree/feature/C221

Here are the point that were done :

- in general all the exceptions in the code were checked and logged if it wasn't already the case.

- In the client part a lot of exceptions were logged but there was no feedback to the user in case of error. So a pop was implemented to display a standard error message. This popup warns the user that an error occurred and invite him to check the log for more information

This branch has been merged to the dev

**Comment by fbinfotel** [comment]
I have corrected some issue from this ticket directly on the dev dev branch
