### ISSUE TITLE
Could not find the main class

### ISSUE THREAD

**Issue by shahzad-anwer** [IARC-CSU/CanReg5#46]
I have downloaded and installed CanReg5 on windows 7, from the link http://www.iacr.com.fr/index.php?option=com_content&view=article&id=9:canreg5&catid=68&Itemid=445

But, when i run, it gives me following error.
Could not ﬁnd the main class: canreg.client.CanRegClientApp. Program will exit.

What could be the solution?

**Comment by mortenjohs** [comment]
Dear shahzad-anwer,
What version did you download? The Windows specific installer? (If not I would recommend downloading and running [that](http://www.iacr.com.fr/CanReg5/CanReg5-Setup.zip).) 
If you did download that, or you, for some reason, can't, how did you start the program? Did you unzip everything? If you want to launch it from command line, you need to call: 
`java.exe --jar CanReg.jar` 
Thanks,
Morten

**Comment by temitopefunmi** [comment]
Hi Morten,
I am currently having this issue also. I tried installing the newest version of CanReg5. I get this same error. I also tried running from command line, still the same.
Kindly help.

Thank you

**Comment by temitopefunmi** [comment]
Hi Morten,
I am also having this issue and i have tried re-downloading from this iarc website. I also used the command line prompt and still the same issue.
Kindly help with this.
Thank you.
