### ISSUE TITLE
Allow importing from non-canreg sources

### ISSUE THREAD

**Issue by braiam** [IARC-CSU/CanReg5#47]
It seems that while canreg would be good enough for new cancer registers, it doesn't seem to help established registers to migrate over. Would be possible to add a function to allow importing from other sources?

**Comment by mortenjohs** [comment]
Currently there are two main ways to get data from other sources into CanReg5 in a "batch mode":

1. Generate a file following the format of data exported from CanReg4. (One flat file with all the information per tumour, linking patients using the socalled "MPcodes".)
2. Generate files following the format of data exported from CanReg5. (One file for patient information, one for tumour information, and one for source information adding the foreign keys for the respective tables.)

I agree, though, that a tool to prepare data from other sources could be an interesting addition to CanReg5.

**Comment by braiam** [comment]
Would Canreg import the structure of the source also? It would be a huge leap if the import wizard allows to set the data type and import the dictionaries in a single step.

**Comment by mortenjohs** [comment]
That would, indeed be a good thing, but it is beyond the scope of CanReg5 -- for now...
