### ISSUE TITLE
How to change the directory CanReg uses to store the database?

### ISSUE THREAD

**Issue by braiam** [IARC-CSU/CanReg5#52]
It seems that the directory is hard-coded to be the user home directory. Can this be configurable?

https://github.com/IARC-CSU/CanReg5/blob/99c4644ded8627d5f4f765c5acaa7bb93e7d7770/src/canreg/server/SystemSettings.java#L229

**Comment by mortenjohs** [comment]
This would be a good idea. I've added it to the list of future enhancements.
