### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by liquid36** [IARC-CSU/CanReg5#53]
Hello!
If i want to make my own compilation, where can i get the dependencies? I tried to download then, but there are two or three that i did't find. 
Thanks!

**Comment by mortenjohs** [comment]
Hello,
One way to get the dependencies would be to download the compiled version from htttp://www.iacr.com.fr/CanReg5 .
Thanks,
Morten

**Comment by liquid36** [comment]
Okey! Thanks. We are trying to set the RMI port that Java use randomly. 

we add this line in the constructor of all the classes that extends `UnicastRemoteObject`.

```
   super(1099);
```

What do you thinks? Apparenttly, it's working!

**Comment by mortenjohs** [comment]
That is good news. I'm not sure I like that it is hardcoded (at least 1099 is the default RMI port, it seems). Will this be needed in addition to the port that the user can set during launch/connection?

**Comment by liquid36** [comment]
Yes, RMI connection use two port, default port 1099 and a random port for comunication. Our problem is that we need to open specific ports on the server. We can't  open all the ports. 

Now we are testing your program with those changes and everything seems to be going well. But since I'm not a native Java programmer, I do not know how to make that second port configurable. This part it's up to you.
