### ISSUE TITLE
Pleaaaaaaase help me !!! Can't log in into canreg 5 (server can't be found)!!!

### ISSUE THREAD

**Issue by Mina9186** [IARC-CSU/CanReg5#56]
Dear maintainer,

I'm not a programmer, I'm just a simple user of CanReg5.
Since days, I can't log in to CanReg!!
I use it in french, When I click : "se connecter à Canreg" i get: "serveur déjà lancé" then I see that the name of the server, username and password are cleared from the next log in screen, I don't know what happened, but please help me! How can I log in? 
When I searched in the program files, the repertory with the name of my server is always there, is that mean that my database is always safe? please, it's very important! I work in a hospital and I can't loose this database!

**Comment by mortenjohs** [comment]
Dear @Mina9186 ,

Sorry to hear about your issues with CanReg5. To help you I would need some more information on what has gone wrong. The "serveur déjà lancé"-error message is not enough, I'm afraid. Did you install a new version of Java? What version of CanReg5 do you use? Can you send me an email (ervikm@iarc.fr) with the CanReg5 log file captured after an unsuccessful run? (The logfile is located in your user’s folder, for example: C:\Users\morten\ (you can access this by typing %USERPROFILE% in the address bar of a windows explorer). It is called “canreg5client.log”. (The .log-part might not be displayed, depending on the settings on your computer.))

Your database is most probably safe, but, if you haven't already, I would recommend also using the built in back-up facility.

Thanks,
Morten

**Comment by Mina9186** [comment]
Hello,

Thank you Mr. Morten Ervik for your rapid reply, I could  finaly log in after installing the back up system, thank you a lot for creating the back up option! It have saved my life!

I'm very happy thank you a lot!

**Comment by mortenjohs** [comment]
I'm happy to hear that your problems are solved.
Thanks,
Morten

**Comment by Mina9186** [comment]
Hello Mr. Morten

I hope you are fine, you have helped me once concerning a little issue with your great software and I thank you again.
Today I need your precious help to know how to compare ASR between two registries? Is there a specific statistical test for this? Please I'm a phD student and it is very important in my thesis.

Thank you a lot,

Amina D.,

________________________________
De : Morten Johannes Ervik <notifications@github.com>
Envoyé : lundi 30 avril 2018 14:34
À : IARC-CSU/CanReg5
Cc : Mina9186; Mention
Objet : Re: [IARC-CSU/CanReg5] Pleaaaaaaase help me !!! Can't log in into canreg 5 (server can't be found)!!! (#56)


I'm happy to hear that your problems are solved.
Thanks,
Morten

**Comment by PRECIOUS2K** [comment]
Hello Morten,
Kindly greetings from Ghana.
I just downloaded the Canreg5 application but I'm unable to login using the default login username (morten) and password (ervik).

Meanwhile, no server name appears in the server dialogue box and um guessing that might be the problem.

Please I am practically clueless and what to do and so your help with be grateful appreciated.

How can I solve this problem please?
I have attached a screenshot of my problem.

![login error](https://user-images.githubusercontent.com/104330806/165004572-73da39ef-6f07-4eaf-a006-54f3eec4b561.JPG)

Thanks a lot.

**Comment by mortenjohs** [comment]
Dear Precious,
Thank you for your interest in CanReg5. A regional CanReg expert will get back to you shortly.
Thanks,
Morten

**Comment by PRECIOUS2K** [comment]
Ok.
Thank you very much.



Precious K. Kwadzokpui
Medical Laboratory Scientist
Department of Medical Laboratory Science
University of Health and Allied Sciences, Ho-Ghana
PMB 31
Ho.

Medical Laboratory Scientist
Ho Teaching Hospital
P. O. Box MA 374
Ho - Volta Region
+233 (0) 362 027 319
+233 (0) 206 241 929
***@***.***

Medical Laboratory Scientist
Reinbee Medical Laboratory and Wellness Center
Second Floor, Shepherd Plaza
49A Stadium Road
Ho-Ghana

Email:
***@***.***

**Comment by Million97** [comment]
Hello please help me how to change canreg5 database password?
